<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQhD3cJG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQhD3cJG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQhD3cJG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQhD3cJG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQhD3cJG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QhD3cJG',
    'container.build_id' => '01095201',
    'container.build_time' => 1663057479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQhD3cJG');
